### ISSUE TITLE
Library update

### ISSUE THREAD

**Issue by mcanam** [HYannick/CapoSongs#1]
Hi, i'm Anam. your project is very interesting. and i see if you use liricle. but it seems you are having trouble when reloading the lyrics. so i updated the liricle to make sure the lyrics were loaded before syncing. if there are other problems with liricle, don't hesitate to open new issues. cheers 🥂

**Comment by HYannick** [comment]
Hello @mcanam! Thanks for reaching out! Sorry for the late answer I didn't look at the issues ahah. And yeah I had a small issue about the sync
Thanks for the update gonna check it and update it :)
